# Generated by Django 4.0.7 on 2023-09-10 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StudentID', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('StudentName', models.CharField(max_length=30)),
                ('StudentFace', models.ImageField(upload_to='media/')),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
